### ISSUE TITLE
UI Improvements with Reward Grouping

### ISSUE THREAD

**Issue by joeizang** [yann300/remix-rewards-ui#42]
My only comments now after seeing the newest changes are:

Can the title bars of each badge be blue background and white type, like the original site? It would anchor each module nicely, and it would set off the titles from the list of wallet addressed below them. Would also just make the titles look a bit cooler and more anchored to the module, and it would allow for a rollover state consistent with the top nav.
![](https://user-images.githubusercontent.com/35277634/202080501-64cb10b3-416e-4a56-9811-05f105b7e1bc.png)

Since Ulrike made some of the .pngs longer than others, can we describe the module with the longest .png (UX Champion) with the least amount of spacing between badge .png image and title below it? And, use that length of module as the standard length of all other modules. So, shorter .pngs in other modules would have more space between the .png and their title. See image below. Also, see that UX Champion has equal spacing around all edges, bottom, and sides, and top... to image. In other words, I think we can lose some of the space between title field and bottom edge of each module.
![](https://user-images.githubusercontent.com/35277634/202079883-afe2df66-60f7-4e30-9cef-ae9a30d8ccd1.png)

**Comment by vermouth22** [comment]
1. There is an issue with display wherein the modules are slightly different heights, and these heights are no longer dependent on height of .png image displayed in the module. See image... 
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/35277634/204704697-df140748-f7d2-409f-a9cf-bf779ef20740.png">
2. Can the bottom edge of the blue label of each module be closer to the bottom edge of the module? This will save space.
3. Can the listed items below the blue label title be a white background to offset it from the blue label? We could handle this in the other issue about the accordian layer though, too.
